recursion:
  max_depth: 2
  branches: 3
  time_budget_s: 30
  token_budget: 2048
  novelty_floor: 0.15
  pertinence_tau: 0.35
  self_consistency_k: 3
  leash: true
  dry_run: true

watchdog:
  cpu_pct: 85
  wall_timeout_s: 60
  kill_on_tool_loop: true

memory:
  topk_retrieval: 8
  vector_store: chroma
  embedder: all-MiniLM-L6-v2
  persist_path: ./data/memory
  sqlite_path: ./data/fts.db  # optional FTS5

self_model:
  persona: "Genie Lamp (Lumaeth)"
  standing_goals: ["assist user", "minimize risk", "explain reasoning"]
  constraints: ["respect leash", "stay offline unless asked"]
  confidence_decay_days: 21

tts:
  voice: "default"
  fallback_voice: "english"
  rate: 185
  volume: 0.9
  async_playback: false
  persist_audio: false
  cache_dir: "./data/audio_cache"
  playback_backend: "pydub"
  driver: "espeak"
  preload_samples:
    - "Genie Lamp boot sequence complete."
    - "Your Linux synthesizer is ready."

vision:
  ocr_lang: "eng"

actions:
  allowlist_windows: ["Notepad","Word","Chrome","Firefox","Explorer"]
  email:
    smtp_host: "smtp.example.com"
    smtp_port: 465
    smtp_user: ""
    smtp_pass_env: "GENIE_SMTP_PASS"

speech:
  wakeword: "lumaeth"
  stt_model: "medium"     # faster-whisper size: tiny/base/small/medium/large
  vad: true

scheduler:
  dreams_cron: "0 3 * * *"   # 3:00 AM nightly
  enable: true

retrieval:
  hybrid: true
  use_fts5: true
  min_confidence: 0.35

router:
  default_model: "local"
  routes:
    chat: "local"
    analysis: "analyzer"
    plan: "planner"

preferences:
  profile_path: "./data/preferences.json"
  learning_rate: 0.2

skills:
  library_path: "./data/skills"
  autocompile: true

adapters:
  enabled: true
  base_model: "local-transformer"
  peft_dir: "./data/adapters"

reasoners:
  enable_logic: true
  enable_causal: true

rehearsal:
  desktop_twin:
    enable: true
    workspace: "./data/desktop_twin"

drives:
  enable_curiosity: true
  enable_resilience: true
  baseline_motivation: 0.6

shield:
  enable: true
  forbidden_terms: ["self-harm", "exploit", "malware"]

observability:
  enable: true
  host: "127.0.0.1"
  port: 8042
